/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ShopAllRouteImport } from './routes/shop/all'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminNewProductRouteImport } from './routes/admin/new-product'
import { Route as AdminNewHeroRouteImport } from './routes/admin/new-hero'
import { Route as AdminNewCategoryRouteImport } from './routes/admin/new-category'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAboutRouteImport } from './routes/admin/about'
import { Route as AdminInquiryIdRouteImport } from './routes/admin/inquiry/$id'
import { Route as AdminEditProductIdRouteImport } from './routes/admin/edit-product/$id'
import { Route as AdminEditHeroIdRouteImport } from './routes/admin/edit-hero/$id'
import { Route as AdminEditCategoryIdRouteImport } from './routes/admin/edit-category.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAllRoute = ShopAllRouteImport.update({
  id: '/shop/all',
  path: '/shop/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewProductRoute = AdminNewProductRouteImport.update({
  id: '/admin/new-product',
  path: '/admin/new-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewHeroRoute = AdminNewHeroRouteImport.update({
  id: '/admin/new-hero',
  path: '/admin/new-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewCategoryRoute = AdminNewCategoryRouteImport.update({
  id: '/admin/new-category',
  path: '/admin/new-category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiryIdRoute = AdminInquiryIdRouteImport.update({
  id: '/admin/inquiry/$id',
  path: '/admin/inquiry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditProductIdRoute = AdminEditProductIdRouteImport.update({
  id: '/admin/edit-product/$id',
  path: '/admin/edit-product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditHeroIdRoute = AdminEditHeroIdRouteImport.update({
  id: '/admin/edit-hero/$id',
  path: '/admin/edit-hero/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditCategoryIdRoute = AdminEditCategoryIdRouteImport.update({
  id: '/admin/edit-category/$id',
  path: '/admin/edit-category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new-category': typeof AdminNewCategoryRoute
  '/admin/new-hero': typeof AdminNewHeroRoute
  '/admin/new-product': typeof AdminNewProductRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/all': typeof ShopAllRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/edit-category/$id': typeof AdminEditCategoryIdRoute
  '/admin/edit-hero/$id': typeof AdminEditHeroIdRoute
  '/admin/edit-product/$id': typeof AdminEditProductIdRoute
  '/admin/inquiry/$id': typeof AdminInquiryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new-category': typeof AdminNewCategoryRoute
  '/admin/new-hero': typeof AdminNewHeroRoute
  '/admin/new-product': typeof AdminNewProductRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/all': typeof ShopAllRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/edit-category/$id': typeof AdminEditCategoryIdRoute
  '/admin/edit-hero/$id': typeof AdminEditHeroIdRoute
  '/admin/edit-product/$id': typeof AdminEditProductIdRoute
  '/admin/inquiry/$id': typeof AdminInquiryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new-category': typeof AdminNewCategoryRoute
  '/admin/new-hero': typeof AdminNewHeroRoute
  '/admin/new-product': typeof AdminNewProductRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/all': typeof ShopAllRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/edit-category/$id': typeof AdminEditCategoryIdRoute
  '/admin/edit-hero/$id': typeof AdminEditHeroIdRoute
  '/admin/edit-product/$id': typeof AdminEditProductIdRoute
  '/admin/inquiry/$id': typeof AdminInquiryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/about'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/new-category'
    | '/admin/new-hero'
    | '/admin/new-product'
    | '/admin/products'
    | '/admin/settings'
    | '/product/$slug'
    | '/shop/$slug'
    | '/shop/all'
    | '/about/'
    | '/admin/'
    | '/contact/'
    | '/shop/'
    | '/admin/edit-category/$id'
    | '/admin/edit-hero/$id'
    | '/admin/edit-product/$id'
    | '/admin/inquiry/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/about'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/new-category'
    | '/admin/new-hero'
    | '/admin/new-product'
    | '/admin/products'
    | '/admin/settings'
    | '/product/$slug'
    | '/shop/$slug'
    | '/shop/all'
    | '/about'
    | '/admin'
    | '/contact'
    | '/shop'
    | '/admin/edit-category/$id'
    | '/admin/edit-hero/$id'
    | '/admin/edit-product/$id'
    | '/admin/inquiry/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/about'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/new-category'
    | '/admin/new-hero'
    | '/admin/new-product'
    | '/admin/products'
    | '/admin/settings'
    | '/product/$slug'
    | '/shop/$slug'
    | '/shop/all'
    | '/about/'
    | '/admin/'
    | '/contact/'
    | '/shop/'
    | '/admin/edit-category/$id'
    | '/admin/edit-hero/$id'
    | '/admin/edit-product/$id'
    | '/admin/inquiry/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewCategoryRoute: typeof AdminNewCategoryRoute
  AdminNewHeroRoute: typeof AdminNewHeroRoute
  AdminNewProductRoute: typeof AdminNewProductRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopAllRoute: typeof ShopAllRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  AdminEditCategoryIdRoute: typeof AdminEditCategoryIdRoute
  AdminEditHeroIdRoute: typeof AdminEditHeroIdRoute
  AdminEditProductIdRoute: typeof AdminEditProductIdRoute
  AdminInquiryIdRoute: typeof AdminInquiryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/all': {
      id: '/shop/all'
      path: '/shop/all'
      fullPath: '/shop/all'
      preLoaderRoute: typeof ShopAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-product': {
      id: '/admin/new-product'
      path: '/admin/new-product'
      fullPath: '/admin/new-product'
      preLoaderRoute: typeof AdminNewProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-hero': {
      id: '/admin/new-hero'
      path: '/admin/new-hero'
      fullPath: '/admin/new-hero'
      preLoaderRoute: typeof AdminNewHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-category': {
      id: '/admin/new-category'
      path: '/admin/new-category'
      fullPath: '/admin/new-category'
      preLoaderRoute: typeof AdminNewCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiry/$id': {
      id: '/admin/inquiry/$id'
      path: '/admin/inquiry/$id'
      fullPath: '/admin/inquiry/$id'
      preLoaderRoute: typeof AdminInquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-product/$id': {
      id: '/admin/edit-product/$id'
      path: '/admin/edit-product/$id'
      fullPath: '/admin/edit-product/$id'
      preLoaderRoute: typeof AdminEditProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-hero/$id': {
      id: '/admin/edit-hero/$id'
      path: '/admin/edit-hero/$id'
      fullPath: '/admin/edit-hero/$id'
      preLoaderRoute: typeof AdminEditHeroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-category/$id': {
      id: '/admin/edit-category/$id'
      path: '/admin/edit-category/$id'
      fullPath: '/admin/edit-category/$id'
      preLoaderRoute: typeof AdminEditCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewCategoryRoute: AdminNewCategoryRoute,
  AdminNewHeroRoute: AdminNewHeroRoute,
  AdminNewProductRoute: AdminNewProductRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopAllRoute: ShopAllRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  AdminEditCategoryIdRoute: AdminEditCategoryIdRoute,
  AdminEditHeroIdRoute: AdminEditHeroIdRoute,
  AdminEditProductIdRoute: AdminEditProductIdRoute,
  AdminInquiryIdRoute: AdminInquiryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
